### ISSUE TITLE
cant open order UI and cant save squad in multiplayer

### ISSUE THREAD

**Issue by parker-nelson** [The-Fireplace/Overlord#258] opened 2023-04-15 13:37 UTC
in minecraft version 1.18, i am unable to save a new squad, and use the orders wand/ orders button to control my skeletons, but it works in single player

**Comment by fireblade1576** [comment] 2024-03-11 08:34
Same here, 1.18.2 minecraft on a modded server. Got a skele to spawn and everything but even with the order wand I couldn't tell the skeleton to do anything. Hitting orders on the skeletons screen didn't load anything, Tried creating a squad but it just said "Saving squad" for like 10 mins before I gave up and hit esc to cancel it. 
Idk what could remotely be causing an issue like this, the spawned skeletons just follow me around nonstop like this.
Am using the latest 1.18.2 Overlord version for forge, w/ the most recent forge version for 1.18.2 MC.

**Comment by The-Fireplace** [comment] 2024-04-08 01:56
Duplicate of #247

**Comment by The-Fireplace** [comment] 2024-04-08 01:57
Duplicate of #247

**Closed as not planned by The-Fireplace** 2024-04-08 01:56 UTC
Labels: bug, duplicate
