### ISSUE TITLE
high usage of memory and lag (when change the skins of skeletons)

### ISSUE THREAD

**Issue by Lightone** [The-Fireplace/Overlord#32] opened 2016-10-10 22:08 UTC
while you play with the skeletons normally, dont have any problem, but when you change the skins of any of them the usage of memory rise.

Normal skins
![memoryanormal](https://cloud.githubusercontent.com/assets/2113099/19252511/d9ba8fa0-8f0a-11e6-99be-9579bbc82488.png)

With skins in few minutes
![highusagememory](https://cloud.githubusercontent.com/assets/2113099/19252563/1bb9e446-8f0b-11e6-9251-91d6bed31af6.png)

forge (1.10.2-12.18.1.2073)
Java (jre1.8.0_101)

[Last Logs](http://pastebin.com/nkfjS5CY)

**Comment by The-Fireplace** [comment] 2016-10-10 22:14
Interesting, I will definitely have to look in to that. Thanks for the
report.

**Comment by The-Fireplace** [comment] 2016-10-11 03:32
@Lightone It is fixed now in version 1.1.5. Thanks you again for reporting that, I wouldn't have ever noticed.

**Comment by Lightone** [comment] 2016-10-11 14:09
@The-Fireplace  The memory leak. (persist) (Overlord-1.1.5) ) i found something interesting about that (only the memory rise when you look the skeletons when have the skin change with other skins different of steve ) if you look in other dirrections the memory stop to rise, but is you look again the memory beging to rise and dont decrease.

Tested in flat world only with forge.

**Comment by The-Fireplace** [comment] 2016-10-11 14:28
@Lightone ok, I will see if I can get it to stop doing that. 1.1.5 definitely improved it, because I was able to monitor before and after that update and it was greatly improved.

**Comment by The-Fireplace** [comment] 2016-10-11 14:30
@Lightone Would you press Shift+F3 and send me a screenshot when the memory usage is high? The pie chart would be useful.

**Comment by Lightone** [comment] 2016-10-11 15:21
@The-Fireplace  Usage memory and Pie debug 
![usage memory](https://cloud.githubusercontent.com/assets/2113099/19276564/614f7430-8f9c-11e6-9eb3-bba131802744.png)

![2016-10-11_10 12 49](https://cloud.githubusercontent.com/assets/2113099/19276579/6f7bf02e-8f9c-11e6-8279-9cddb0bd6c28.png)

**Comment by The-Fireplace** [comment] 2016-10-11 16:34
@Lightone thanks. I'll fix it asap, and comment on here again when it is fixed.

**Comment by The-Fireplace** [comment] 2016-10-11 17:59
@Lightone I can't seem to reproduce the issue quite yet, but I am still investigating. One thing I can suggest is updating to Forge 12.18.1.2093 or later, as it fixes a Forge bug and should give you about 10% better performance.

**Comment by Lightone** [comment] 2016-10-11 22:02
@The-Fireplace i test with forge 93 and 99 recommeded version but is the same result the memory rise but more slower right now, but rise.

I do other test with AMD machine and the result is the same meaby i have bad luck with yours mod xD.

i notice the flashing in the right side of the skins is happend while the skeletons have the skins any type .

![issueskins](https://cloud.githubusercontent.com/assets/2113099/19290189/1e554096-8fd4-11e6-82e2-43c927258642.gif)

only the default skins of steve work fine, the memory dont rise with this skins.

**Comment by The-Fireplace** [comment] 2016-10-11 22:31
@Lightone the flashing can't be easily fixed, but it isn't part of the problem. And I know using the newer Forge version doesn't completely fix it, I was just trying to help you out. I'm still having difficulty finding the exact problem, but I have noticed that it happens on my computer too. Very slowly.

**Comment by The-Fireplace** [comment] 2016-10-15 17:13
1.2.1 fixes this issue. If you continue to have issues, I suggest updating Java and allocating more RAM to Minecraft.

**Closed as completed by The-Fireplace** 2016-10-15 17:13 UTC
Labels: bug

**Comment by Lightone** [comment] 2016-10-16 16:32
Finally fixed the memory rise. 

The issue #41 is different is no memory rise is problem heavy lag when the you rename  the skinsuit and the result when change the skins is a default steve. 

Tested (1.2.1)

**Comment by The-Fireplace** [comment] 2016-10-16 16:41
@Lightone if the lag wasn't caused by high memory usage then there's nothing I can do. Try tweaking graphics settings (If VBOs are on, try turning them off, that may help when you have integrated graphics). Another thing you could try is going in to the mod Config and disabling Ghostly Skinsuits.
